# Since our non-Windows ports are not finished, Travis is currently only used
# to deploy the documentation.

language: cpp

sudo: false

# Blacklist
branches:
  only:
    - develop

# Environment variables
env:
  global:
    - GH_REPO_NAME: lwpa
    - GH_REPO_REF: github.com/ETCLabs/lwpa.git
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile

if: branch = develop
  env:
    global:
      - DOCS_PUBLISH_DIR: head
      - DOCS_VERSION_NUMBER: "HEAD (unstable)"

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - /bin/true

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/tools/ci
  - chmod +x publish_docs.sh
  - ./publish_docs.sh
