# Since our non-Windows ports are not finished, Travis is currently only used
# to deploy the documentation.

language: cpp

sudo: false

# Blacklist
branches:
  only:
    - develop

# Environment variables
env:
  global:
    - GH_REPO_NAME: lwpa
    - GH_REPO_REF: github.com/ETCLabs/lwpa.git

# Install dependencies

stages:
  - test
  - name: docs
    if: branch = develop

jobs:
  include:
    - script: skip
    # Generate and deploy documentation
    - stage: docs
      addons:
        apt:
          packages:
            - doxygen
      script:
        - cd $TRAVIS_BUILD_DIR/tools/ci
        - chmod +x publish_docs.sh
        - ./publish_docs.sh
