# Since our non-Windows ports are not finished, Travis is currently only used
# to deploy the documentation.

language: cpp

sudo: required

# Blacklist
branches:
  only:
    - develop

# Environment variables
env:
  global:
    - GH_REPO_NAME: lwpa
    - GH_REPO_REF: github.com/ETCLabs/lwpa.git

# Install dependencies

stages:
  - test
  - name: docs
    if: branch = develop

jobs:
  include:
    - script: skip
    # Generate and deploy documentation
    - stage: docs
      # TODO - we need to install doxygen like this for now because of older
      # distros on Travis. Once Doxygen support gets up to 1.8 or so we can use
      # apt-get.
      before_script:
        - wget http://ftp.stack.nl/pub/users/dmitri/doxygen-1.8.14.linux.bin.tar.gz
        - tar -xzf doxygen-1.8.14.linux.bin.tar.gz
        - cd doxygen-1.8.14
        - ./configure
        - sudo make install || true
      script:
        - cd $TRAVIS_BUILD_DIR/tools/ci
        - chmod +x publish_docs.sh
        - ./publish_docs.sh
