# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: develop
pr: develop

- job: Windows Build and Test
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Debug:
        BUILD_CONFIG: 'Debug'
      Release:
        BUILD_CONFIG: 'Release'
  steps:
  - displayName: 'lwpa Windows build'
    script: |
      mkdir build
      cd build
      cmake --version
      cmake -G "Visual Studio 15 2017 Win64" ..
      cmake --build . --config %BUILD_CONFIG%
  - displayName: 'lwpa Windows test'
    script: tests\%BUILD_CONFIG%\test_lwpa.exe
