# The lwpa build and test pipeline.

trigger:
- develop

pr:
- develop

jobs:
- job: Windows Build and Test
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Debug:
        BUILD_CONFIG: 'Debug'
      Release:
        BUILD_CONFIG: 'Release'
  steps:
  - script: |
      mkdir build
      cd build
      cmake --version
      cmake -G "Visual Studio 15 2017 Win64" ..
      cmake --build . --config %BUILD_CONFIG%
    displayName: 'lwpa Windows build'
  - script: tests\%BUILD_CONFIG%\test_lwpa.exe
    displayName: 'lwpa Windows test'
