# The EtcPal build and test pipeline.

trigger:
- develop
- master
- release/*

pr:
- develop

variables:
  cmake_definitions: -DETCPAL_BUILD_MOCK_LIB=ON -DETCPAL_BUILDING_FOR_AZURE_PIPELINES_CI=1

jobs:
# Build and test EtcPal on Windows using CMake and Visual Studio 2019.
- job: windows_build
  displayName: 'Windows Build and Test'
  pool:
    vmImage: 'windows-2019'
  variables:
    cmake_generator: 'Visual Studio 16 2019'
  steps:
  - script: |
      mkdir build
      cd build
      cmake --version
      cmake -G "$(cmake_generator)" -A x64 $(cmake_definitions) ..
      cmake --build . --config Release
    displayName: 'EtcPal Windows build'
  - script: |
      cd build
      ctest --verbose -C Release
    displayName: 'EtcPal Windows test'

- job: macos_build
  displayName: 'macOS Build and Test'
  pool:
    vmImage: 'macos-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake --version
      cmake $(cmake_definitions) ..
      cmake --build .
    displayName: 'EtcPal macOS build'
  - script: |
      cd build
      ctest --verbose
    displayName: 'EtcPal macOS test'

- job: linux_build
  displayName: 'Linux Build and Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install uuid-dev
      mkdir build
      cd build
      cmake --version
      cmake -G "Unix Makefiles" $(cmake_definitions) ..
      cmake --build .
    displayName: 'EtcPal Linux build'
  - script: |
      cd build
      ctest --verbose
    displayName: 'EtcPal Linux test'

# Generate documentation with doxygen. Documentation is generated from the
# develop branch and posted to the 'head' portion of the Github page
# (etclabs.github.io/EtcPal)
- job: docs
  displayName: 'Deploy documentation'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  pool:
    vmImage: 'ubuntu-latest'
  variables: 
  - group: github-push-access
  steps:
  - script: sudo apt-get install doxygen
    displayName: 'Install dependencies'
  - script: |
      cd tools/ci
      chmod +x publish_docs.sh
      ./publish_docs.sh
    displayName: 'Generate and deploy documentation'
    env:
      GH_REPO_NAME: EtcPal
      GH_REPO_REF: github.com/ETCLabs/EtcPal.git
      GH_REPO_TOKEN: $(GH_ACCESS_TOKEN)
  